# Position sizing strategy configuration
strategy:
  type: 'position-sizing'

# Backtesting Settings
backtesting:
  min_position_change: 0.0618
  exaggerate: True
  compound: True
  enter_threshold: 0.53
