# Quantum strategy configuration
strategy:
  type: 'quantum'

# Backtesting Settings
backtesting:
  exit_threshold: 0.50
  enter_threshold: 0.53
  hedge_threshold: 0.618
  stop_loss: 0.1
  initial_balance: 1