# Quantum strategy configuration
strategy:
  type: 'quantum'
  exit_threshold: 0.48
  enter_threshold: 0.53
  hedge_threshold: 0.618
  stop_loss: 0
  risk_reward_ratio: 0.618
  initial_balance: 1
  threshold_bias: 1.0256
