# Copy this file to api_keys.yaml and fill in your API keys
# NEVER commit the actual api_keys.yaml file with real credentials

binance:
  api_key: YOUR_API_KEY_HERE
  api_secret: YOUR_API_SECRET_HERE
  testnet: true  # Set to false for production

kraken:
  api_key: YOUR_API_KEY_HERE
  api_secret: YOUR_API_SECRET_HERE

bybit:
  api_key: YOUR_API_KEY_HERE
  api_secret: YOUR_API_SECRET_HERE
  testnet: true  # Set to false for production

okx:
  api_key: YOUR_API_KEY_HERE
  api_secret: YOUR_API_SECRET_HERE
  password: YOUR_API_PASSWORD_HERE  # OKX requires a password/passphrase
  testnet: true

kucoin:
  api_key: YOUR_API_KEY_HERE
  api_secret: YOUR_API_SECRET_HERE
  passphrase: YOUR_API_PASSPHRASE_HERE  # KuCoin requires a passphrase
  testnet: true