# Data Collection Settings
data:
  timeframes:
    - 15m
  symbols:
    - BTC/USDT
  start_date: 2011-01-01
  exchanges:
    - binance
    - kraken
    - kucoin
  alternative_sources:
    - yfinance
    - cryptocompare
  path: data
  raw:
    path: data/raw
  processed:
    path: data/processed
  reservoir:
    path: data/reservoir
    reservoir_size: 1000000
    reservoir_sample_size: 100000

# Model Settings
model:
  type: 'enhanced_bayesian'
  path: models

# Strategy Settings
strategy:
  type: 'quantum'
  path: strategies

# Training Settings
training:
  memory_efficient: True
  test_size: 0.05     # Small test size
  max_memory_mb: 16000  # Memory limit
  max_samples_per_batch: 100000 # Max samples per batch
  min_profit_target: 0.01 # Minimum profit target

  incremental_training:
    chunk_size: 100000
    overlap: 5000
    checkpoint_frequency: 1  # Save after each chunk
  
# Backtesting Settings
backtesting:
  exit_threshold: 0.3
  stop_loss: 0.1
  initial_balance: 1
  min_position_change: 0.1
  exaggerate: False
  test_sets:
    custom_test_set: None
    path: data/test_sets
  # slippage: 0.001
  # leverage: 1
  # max_open_trades: 0
  # max_holding_time: 1000
  # max_open_time: 1000
  # max_open_trades_per_symbol: 1
  # max_open_trades_per_side: 1
  # max_open_trades_per_symbol_per_side: 1
  results:
    path: data/backtest_results

walk_forward:
  train_window: 180  # Training window in ticks
  test_window: 30    # Testing window in ticks
  step_size: 30      # Step size in ticks
  min_train_samples: 1000  # Minimum samples needed for training

exchange:
  fee_rate: 0.006