# Data Collection Settings
data:
  timeframes:
    - 15m
  symbols:
    - BTC/USDT
  start_date: 2011-01-01
  exchanges:
    - binance
    - kraken
    - kucoin
  alternative_sources:
    - yfinance
    - cryptocompare

# Model Settings
model:
  type: 'enhanced_bayesian'
  max_samples_per_batch: 50000
  feature_cols:
    - bb_pos
    - RSI_14
    - MACDh_12_26_9
    - trend_strength
    - volatility
    - volume_ratio
    - range
    - macd_hist_diff
    - rsi_diff
    - bb_squeeze

training:
  memory_efficient: True
  
# Backtesting Settings
backtesting:
  exit_threshold: 0.03
  stop_loss: 0.03
  initial_balance: 1
  fee_rate: 0.006
  min_position_change: 0.025
  # slippage: 0.001
  # leverage: 1
  # max_open_trades: 0
  # max_holding_time: 1000
  # max_open_time: 1000
  # max_open_trades_per_symbol: 1
  # max_open_trades_per_side: 1
  # max_open_trades_per_symbol_per_side: 1

walk_forward:
  train_window: 180  # Training window in ticks
  test_window: 30    # Testing window in ticks
  step_size: 30      # Step size in ticks
  min_train_samples: 1000  # Minimum samples needed for training