# Data Collection Settings
data:
  timeframes:
    - 1m
    - 5m
    - 15m
    - 1h
    - 4h
  symbols:
    - BTC/USD
    - ETH/USD
    - BTC/USDT
    - ETH/USDT
  start_date: 2011-01-01
  exchanges:
    - binance
    - kraken
    - kucoin
  alternative_sources:
    - yfinance
    - cryptocompare

# Backtesting Settings
walk_forward:
  train_window: 180  # Training window in ticks
  test_window: 30    # Testing window in ticks
  step_size: 30      # Step size in ticks
  min_train_samples: 1000  # Minimum samples needed for training