# Data Collection Settings
data:
  model:
    type: 'tf_bayesian'
    feature_cols:
      - bb_pos
      - RSI_14
      - MACDh_12_26_9
      - trend_strength
      - volatility
      - volume_ratio
      - range
      - macd_hist_diff
      - rsi_diff
      - bb_squeeze
  timeframes:
    - 1m
  symbols:
    - BTC/USDT
  start_date: 2011-01-01
  exchanges:
    - binance
    - kraken
    - kucoin
  alternative_sources:
    - yfinance
    - cryptocompare

# Backtesting Settings
walk_forward:
  train_window: 180  # Training window in ticks
  test_window: 30    # Testing window in ticks
  step_size: 30      # Step size in ticks
  min_train_samples: 1000  # Minimum samples needed for training